### PR TITLE
Update default slapd config to support ldaps if ssl cert are installed

### PR DESCRIPTION
**Pull request by rhuang2014**
### Description

Updated default slapd config template to support ldaps protocol if the ssl cert is defined.
### Issues Resolved

None.
### Check List
- [ ] All tests pass. See https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/TESTING.MD
- [ ] New functionality includes testing.
- [ ] New functionality has been documented in the README if applicable
- [ ] The CLA has been signed. See https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/CONTRIBUTING.MD

### CODE REVIEW

**Comment by tas50** [comment]
I'm working on changing how we handle the whole TLS process. We have an attribute now to enable TLS. Is there any reason we wouldn't just enable it automatically with that? It seems like just about everyone is going to be enabling this in 2016.

**Comment by tas50** [comment]
https://github.com/chef-cookbooks/openldap/blob/master/attributes/default.rb#L68 is the attribute btw

**Comment by cheeseplus** [comment]
There is definitely a case for adding certs but NOT turning on LDAPS as you can still initiate StartTLS over LDAP (389).

**Comment by cheeseplus** [comment]
Unfortunately this PR is platform specific in implementation so I'm closing it out but this will be added in the refactor underway.

**Pull request closed without merging**
